apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: brian-k8s-multi-com-tls
spec:
  secretName: brian-k8s-multi-hillghost-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: brian-k8s-multi.hillghost.com
  dnsNames:
    - brian-k8s-multi.hillghost.com
    - www.brian-k8s-multi.hillghost.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - brian-k8s-multi.hillghost.com
          - www.brian-k8s-multi.hillghost.com